### ISSUE TITLE
Broken link in README.md: "published web"

### ISSUE THREAD

**Issue by jubilatious1** [Raku/survey#1]
Link below isn't working:

```
Probably better seen in
this [published web](https://perl6.github.io/p6survey/)
```

**Comment by JJ** [comment]
Gotcha. I'll see what's the matter. Thanks!

**Comment by JJ** [comment]
Yep, moved to https://raku.github.io/survey/ . Will fix.

El mar., 25 ago. 2020 a las 18:54, JJ Merelo (<jjmerelo@gmail.com>)
escribió:

> Gotcha. I'll see what's the matter. Thanks!
>
>
>

-- 
JJ
